#Mon Feb 05 16:22:17 UTC 2024
version=1.0.5-ktor3
GROUP=io.github.guyaumetremblay
POM_ARTIFACT_ID=killswitch
VERSION_NAME=1.0.5-ktor3
POM_NAME=Killswitch Mobile
POM_INCEPTION_YEAR=2023
POM_DESCRIPTION=Killswitch Mobile
POM_URL=https://github.com/guyaumetremblay/killswitch-mobile
POM_SCM_URL=https://github.com/guyaumetremblay/killswitch-mobile
POM_SCM_CONNECTION=scm:git:git://github.com/guyaumetremblay/killswitch-mobile.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/guyaumetremblay/killswitch-mobile.git
POM_LICENCE_NAME=BSD 3-Clause License
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=guyaumetremblay
POM_DEVELOPER_NAME=Guyaume Tremblay
POM_DEVELOPER_URL=https://github.com/guyaumetremblay/
