name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: macos-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v3
        with:
          key: kotlin-native-${{ hashFiles('gradle.properties') }}
          path: ~/.konan

      - uses: gradle/actions/setup-gradle@v5
      - name: Build project
        shell: bash
        run: |
          ./gradlew assemble
      - name: Publish to Maven Central
        shell: bash
        run: |
          ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
